random_forest:
  n_estimators: 100
  max_depth: 15
  min_samples_split: 4
  min_samples_leaf: 3
  n_jobs: -1     # Here -1 means all available cores
  criterion: 'entropy'
  max_features: 0.5
  oob_score: true
decision_tree:
  max_depth: 15
  min_samples_split: 4
  min_samples_leaf: 3
  criterion: 'entropy'